#!/bin/sh

MODULE="scull"
DEVICE="scull"

case "$1" in

    start)
        echo "Loading scull module"

        modprobe ${MODULE} || exit 1

        major=$(awk '$2=="scull" {print $1}' /proc/devices)

        if [ -z "$major" ]; then
            echo "Unable to find scull major number"
            exit 1
        fi

        rm -f /dev/scull /dev/scull[0-3]

        mknod /dev/scull0 c ${major} 0
        mknod /dev/scull1 c ${major} 1
        mknod /dev/scull2 c ${major} 2
        mknod /dev/scull3 c ${major} 3

        ln -sf scull0 /dev/scull

        chmod 664 /dev/scull[0-3]

        echo "scull module loaded"
        ;;

    stop)
        echo "Unloading scull module"

        rm -f /dev/scull /dev/scull[0-3]

        rmmod ${MODULE} 2>/dev/null || true
        ;;

    restart)
        "$0" stop
        "$0" start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;

esac

exit 0